Use a correct regex of filter exported symbols
boost 1.76 on macOS requires two symbols: `PyInit_glom_1_32` and `init_module_glom_1_32`.

It is clear that the old regex `^_*initglom` filter everything that leads to:
```
ImportError: dynamic module does not define module export function (PyInit_glom_1_32)
```